### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError) on OS X El Capitan 

### ISSUE THREAD

**Issue by maximveksler** [aanand/git-up#96]
```
Maxims-MacBook-Pro:GeohashKit maximveksler$ gem install git-up


Fetching: colored-1.2.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

```
Maxims-MacBook-Pro:GeohashKit maximveksler$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11 (15A204h)
      Kernel Version: Darwin 15.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Maxim’s MacBook Pro
      User Name: Maxim Veksler (maximveksler)
      Secure Virtual Memory: Enabled
      Time since boot: 1 day3:51

Maxims-MacBook-Pro:GeohashKit maximveksler$ ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
```

**Comment by nbrew** [comment]
Hi @maximveksler. I do not think your error is specific to git-up. You are seeing this issue because you are trying to install into a directory owned by a user other than yourself. (I believe `/Library/Ruby/Gems/2.0.0` is installed by Apple as part of Mac OS X.)

You have two options:
a) Elevate your user permissions by using `sudo` when running the gem install command

     sudo gem install git-up

b) Or, and this is my preferred route, install a ruby version manager, like [rbenv](https://github.com/sstephenson/rbenv#installation), which can be installed using [homebrew](http://brew.sh) and build your own ruby and gems. This would permit you to install ruby and whatever gems you'd like without modifying the the ruby installed by Apple.

That said, the quick and dirty method using `sudo` will get git-up installed. If you are interested in exploring additional software for your machine, Homebrew is an easy way to install third-party applications and command line tools.

Also, [this StackOverflow question](http://stackoverflow.com/questions/14607193/installing-gem-or-updating-rubygems-fails-with-permissions-error) may assist you.

**Comment by maximveksler** [comment]
I can confirm that using rbenv I was able to get ```git up``` running on my El Capitan system. I've documented the basic steps required here https://github.com/maximveksler/null/wiki/Mac-Hacker-Install-Guide#ruby

I wonder if a more streamlined solution would be possible to implement? perhaps based on ```brew install git-up```.

I shall close this issue for now.

**Comment by nacho4d** [comment]
I varely use ruby. So i dont use rbenv or alikes. Git-up should work without showing any warning messages i think. I like the idea of having it in brew would be even better.

brew install  git-up
